### ISSUE TITLE
How to use this mm2 to migrate topics from confluent kafka to eks kafka cluster.

### ISSUE THREAD

**Issue by shristiopstree** [mroiter-larus/kafka-docker-mm2#5]
when running  connect-mirror-maker /tmp/kafka/config/mm2.properties
getting error Node -1 disconnected

and 

appuser@broker1B ~]$ kafka-console-consumer --bootstrap-server broker1B:29094 --topic clusterA.topic1 --from-beginning
[2024-01-23 13:52:42,314] WARN [Consumer clientId=console-consumer, groupId=console-consumer-25064] Error while fetching metadata with correlation id 2 : {clusterA.topic1=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)

Could you please help in identifying the problem.

**Comment by mroiter-larus** [comment]
Hi @shristiopstree,

are you sure the 2 clusters are correctly up and running? please check the docker logs and share the complete stacktrace, if there are some errors during the startup process, so that i can try to understand what is going on.

However, according to the docker-compose file, the `broker1B` container exposes port 29093 (not 29094). So, you should run 

```
kafka-console-consumer --bootstrap-server broker1B:29093 --topic clusterA.topic1 --from-beginning
```

**Comment by mroiter-larus** [comment]
@shristiopstree any update?

**Comment by mroiter-larus** [comment]
@shristiopstree since there are no updates in the last week, i'm going to close this issue. Feel free to re-open it when you'll have more details to share
